# Generated by Django 6.0.2 on 2026-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverapplication',
            old_name='background_check_consent',
            new_name='background_consent',
        ),
        migrations.RenameField(
            model_name='driverapplication',
            old_name='license_expiry',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='insurance_document',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driverapplication',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='insurance_file',
            field=models.FileField(default='', upload_to='insurance_files/'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='license_file',
            field=models.FileField(default='', upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='license_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='years_experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
