# Generated by Django 6.0.2 on 2026-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_background_check_consent_driverapplication_background_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
